const people = [
{ word: "CHILD", translation: "NIÑO / NIÑA" },
{ word: "MAN", translation: "HOMBRE" },
{ word: "WOMAN", translation: "MUJER" },
{ word: "GIRL", translation: "CHICA" },
{ word: "BOY", translation: "CHICO" },
{ word: "FRIEND", translation: "AMIGO / AMIGA" },
{ word: "STUDENT", translation: "ESTUDIANTE" },
{ word: "TEACHER", translation: "MAESTRO / MAESTRA" },
{ word: "DOCTOR", translation: "DOCTOR / DOCTORA" },
{ word: "NEIGHBOR", translation: "VECINO / VECINA" },
{ word: "WORKER", translation: "TRABAJADOR / TRABAJADORA" },
]


const family =[
{ word: "FAMILY", translation: "FAMILIA" },
{ word: "GRANDPARENTS", translation: "ABUELOS" },
{ word: "GRANDMOTHER", translation: "ABUELA" },
{ word: "GRANDFATHER", translation: "ABUELO" },
{ word: "PARENTS", translation: "PADRES" },
{ word: "FATHER", translation: "PADRE" },
{ word: "MOTHER", translation: "MADRE" },
{ word: "HUSBAND", translation: "ESPOSO" },
{ word: "WIFE", translation: "ESPOSA" },
{ word: "SOON", translation: "HIJO" },
{ word: "DAUGHTER", translation: "HIJA" },
{ word: "GRANDCHILDREN", translation: "NIETOS" },
{ word: "GRANDSON", translation: "NIETO" },
{ word: "GRANDDAUGHTER", translation: "NIETA" },
{ word: "SISTER", translation: "HERMANA" },
{ word: "BROTHER", translation: "HERMANO" },
{ word: "UNCLE", translation: "TÍO" },
{ word: "AUNT", translation: "TÍA" },
{ word: "COUSIN", translation: "PRIMO / PRIMA" },
{ word: "IN-LAWS ", translation: "SUEGROS" },
{ word: "MOTHER-IN-LAW", translation: "SUEGRA" },
{ word: "FATHER-IN-LAW", translation: "SUEGRO" },
{ word: "SISTER-IN-LAW", translation: "CUÑADA" },
{ word: "BROTHER-IN-LAW", translation: "CUÑADO" },
{ word: "NEPHEW", translation: "SOBRINO" },
{ word: "NIECE", translation: "SOBRINA" },
]

const inTheHouse = [
{ word: "ROOM", translation: "HABITACIONES" },
{ word: "BATHROOM", translation: "BAÑO" },
{ word: "BATH", translation: "BAÑERA" },
{ word: "SHOWER", translation: "DUCHA" },
{ word: "BEDROOM", translation: "CUARTO" },
{ word: "BED", translation: "CAMA" },
{ word: "DESK", translation: "ESCRITORIO" },
{ word: "WINDOW", translation: "VENTANA" },
{ word: "CHAIR", translation: "SILLA" },
{ word: "ARMCHAIR", translation: "SILLON (CON APOYA BRAZOS" },
{ word: "SOFA", translation: "SOFÁ" },
{ word: "KITCHEN", translation: "COCINA" },
{ word: "DINING ROOM", translation: "COMEDOR" },
{ word: "TABLE", translation: "MESA" },
{ word: "FRIDGE", translation: "REFRIGERADOR" },
{ word: "DOOR", translation: "PUERTA" },
{ word: "LIVING ROOM", translation: "SALA DE ESTAR" },
{ word: "TV", translation: "TELEVISION" },
{ word: "COFFEE TABLE", translation: "MESA RATONA" },
{ word: "BEDSIDE TABLE", translation: "MESA DE LUZ" },
]

const clothes=[
{ word: "T-SHIRT", translation: "CAMISETA" },
{ word: "SHIRT", translation: "CAMISA" },
{ word: "BLOUSE", translation: "BLUSA" },
{ word: "SHOES", translation: "ZAPATOS" },
{ word: "TIE", translation: "CORBATA" },
{ word: "BELT", translation: "CINTURÓN" },
{ word: "SLIPPERS", translation: "PANTUFLAS" },
{ word: "HEELS", translation: "TACONES" },
{ word: "SNEAKERS", translation: "ZAPATILLAS" },
{ word: "PURSE", translation: "BOLSO" },
{ word: "WALLET", translation: "BILLETERA" },
{ word: "TUX", translation: "ESMOQUIN" },
{ word: "GOWN", translation: "VESTIDO DE FIESTA" },
{ word: "COAT", translation: "ABRIGO" },
{ word: "RAINCOAT", translation: "IMPERMEABLE" },
{ word: "JACKET", translation: "IMPERMEABLE" },
{ word: "VEST", translation: "CHALECO" },
{ word: "SCARF", translation: "SUÉTER" },
{ word: "GLOVES", translation: "GUANTES" },
{ word: "BOOTS", translation: "BOTAS" },
{ word: "SKIRT", translation: "FALDA" },
{ word: "DRESS", translation: "VESTIDO" },
{ word: "HAT", translation: "SOMBRERO" },
{ word: "SWIMSUIT", translation: "TRAJE DE BAÑO" },
{ word: "FLIP FLOPS", translation: "OJOTAS" },
{ word: "SANDALS", translation: "SANDALIAS" },
{ word: "CAP", translation: "GORRA" },
{ word: "SHORT", translation: "PANTALÓN CORTO" },
{ word: "TANK TOP", translation: "CAMISETA SIN MANGA" },
{ word: "SOCK", translation: "SOQUETES" },
{ word: "BRA", translation: "SOSTÉN / SUJETADOR" },
{ word: "THONG", translation: "TANGA" },
{ word: "PANTIES", translation: "BOMBACHA / BRAGAS" },
{ word: "ROBE", translation: "BATA" },
{ word: "UNDERPANTS", translation: "CALZONCILLOS" },
{ word: "BOXERS", translation: "BOXERS" },
{ word: "SLIPPERS", translation: "PANTUFLAS" },
{ word: "HOODIE", translation: "SUDADERA CON CAPUCHA" },
{ word: "PANTS", translation: "PANTALÓN" },
{ word: "SKIRT", translation: "POLLERA" },
]
const food =[
{ word: "COFFEE", translation: "CAFE" },
{ word: "TEA", translation: "TE" },
{ word: "JUICE", translation: "JUGO" },
{ word: "MILK", translation: "LECHE" },
{ word: "BEER", translation: "CERVEZA" },
{ word: "WINE", translation: "VINO" },
{ word: "SODA", translation: "REFRESCO" },
{ word: "LEMONADE", translation: "LIMONADA" },
{ word: "SKIRT", translation: "POLLERA" },
{ word: "FRUITS", translation: "FRUTAS" },
{ word: "APPLE", translation: "MANZANA" },
{ word: "ORANGE", translation: "NARANJA" },
{ word: "TOMATO", translation: "TOMATE" },
{ word: "CARROT", translation: "ZANAHORIA" },
{ word: "LETTUCE", translation: "LECHUGA" },
{ word: "MEAT", translation: "CARNE" },
{ word: "FISH", translation: "PESCADO" },
{ word: "CHICKEN", translation: "POLLO" },
{ word: "BEEF", translation: "CARNE DE VACA" },
{ word: "PORK", translation: "CERDO" },
{ word: "SAUSAGE", translation: "SALCHICHAS" },
{ word: "SEAFOOD", translation: "MARISCOS" },
{ word: "SALMON", translation: "SALMÓN" },
{ word: "YOGURT", translation: "YOGUR" },
{ word: "CHEESE", translation: "QUESO" },
{ word: "BUTTER", translation: "MANTECA" },
{ word: "BREAD", translation: "PAN" },
{ word: "CAKE", translation: "PASTEL" },
{ word: "COOKIES", translation: "GALLETITAS" },
{ word: "EGG", translation: "HUEVOS" },
{ word: "RICE", translation: "ARROZ" },
{ word: "SOUP", translation: "SOPA" },
{ word: "PASTA", translation: "PASTA" },
{ word: "SALAD", translation: "ENSALADA" },
{ word: "HAMBURGER", translation: "HAMBURGUESA" },
{ word: "SALT", translation: "SAL" },
{ word: "PEPPER", translation: "PIMIENTA" },
{ word: "OIL", translation: "ECEITE" },
{ word: "SUGAR", translation: "AZÚCAR" },
]
export default {
  people,
  family,
  inTheHouse,
  clothes,
  food

}