const stranger = [
{ word: "NICE WEATHER WE'RE HAVING", translation: "QUÉ BUEN CLIMA TENEMOS" },
{ word: "MIND IF I SIT HERE?", translation: "¿TE IMPORTA SI ME SIENTO AQUÍ?" },
{ word: "SURE. GO AHEAD ", translation: "CLARO. ADELANTE" },
{ word: "DO YOU KNOW WHAT TIME IT IS?", translation: "¿SABES QUÉ HORA ES?" },
{ word: "DO YOU HAVE THE TIME? ", translation: "¿QUÉ HORA ES?" },
{ word: "DO YOU FROM AROUND HERE? ", translation: "¿ERES DE POR AQUÍ?" },
{ word: "DO YOU CAN HERE OFTEN?", translation: "¿VIENES AQUÍ A MENUDO?" },
{ word: "HI, I'M [YOUR NAME]", translation: "HOLA, SOY [TÚ NOMBRE]" },
{ word: "HI. NICE TO MEET YOU", translation: "HOLA, UN PLACER CONOCERTE" },
{ word: "LIKE-WISE", translation: "IGUALMENTE" },
]

const frends = [
{ word: "HOW'S IT GOING?", translation: "¿CÓMO TE VA?" },
{ word: "HOW ARE THINGS?", translation: "¿CÓMO VAN LAS COSAS?" },
{ word: "HOW HAVE YOU BEEN?", translation: "¿CÓMO HAS ESTADO?" },
{ word: "HOW YOU DOING?", translation: "¿CÓMO ESTAS?"},
{ word: "WHAT'S UP?", translation: "¿QUÉ PASA?" },
{ word: "YOU SEEM A BIT [ADJETIVE].", translation: "PARECES UN POCO [ADJETIVO]." },
{ word: "HOW ARE THINGS WITH [SOMEONE]?", translation: "¿CÓMO VAN LAS COSAS CON [ALGUIEN]?" },
{ word: "THINGS ARE FINE.", translation: "LAS COSAS ESTÁN BIEN." },
{ word: "SAY HI TO [SOMEONE] FOR ME!", translation: "¡SALUDA A [ALGUIEN] DE MI PARTE!" },
{ word: "LET'S GRAB A DRINK SOMETIME.", translation: "TOMEMOS ALGO ALGÚN DÍA" },
{ word: "LONG TIME NO SEE!", translation: "¡MUCHO TIEMPO SIN VERTE!" },
{ word: "LOOK WHO IT IS!", translation: "¡MIRA QUIÉN ESTÁ AQUÍ!" },
{ word: "IT'S BEEN A WHILE!", translation: "¡HA PASADO MUCHO TIEMPO!" },
{ word: "I'M HAPPY TO SEE YOU AGAIN.", translation: "ESTOY FELIZ DE VERTE DE NUEVO." },
{ word: "I HAVEN'T SEEN YOU IN AGES.", translation: "NO TE HE VISTO EN AÑOS." },
{ word: "I'M GLAD I RAN INTO YOU.", translation: "ME ALEGRO DE HABERME ENCONTRADO CONTIGO." },
{ word: "HOW HAVE YOU BEEN?", translation: "¿CÓMO HAS ESTADO?" },
{ word: "HOW'S YOUR DAD/MOM?", translation: "CÓMO ESTA TU PAPÁ/MAMÁ" },
{ word: "WE SHOULD GET TOGETHER SOMETIME.", translation: "DEBERÍAMOS REUNIRNOS ALGUNA VEZ." },
{ word: "DON'T BE A STRANGERS!", translation: "¡NO TE PIERDAS!" },
]
const thank = [
{ word: "THANKS A LOT.", translation: "MUCHAS GRACIAS." },
{ word: "THANKS YOU SO MUCH.", translation: "MUCHAS GRACIAS." },
{ word: "I REALLY APPRECIATE IT.", translation: "REALMENTE LO APRECIO." },
{ word: "MANY THANKS.", translation: "MUCHAS GRACIAS." },
{ word: "THAT'S VERY KIND OF YOU.", translation: "ES MUY AMABLE DE TU PARTE." },
{ word: "ANY TIME", translation: "CUANDO QUIERAS." },
{ word: "GLAD TO HELP", translation: "ENCANTADO DE AYUDAR" },
{ word: "DON'T MENTION IT", translation: "NI LO MENCIONES" },
{ word: "MY PLEASURE.", translation: "UN PLACER." },
{ word: "NO WORRIES.", translation: "NO HAY PROBLEMA" },
]
const responds_to_good_news = [
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
{ word: "", translation: "" },
]
export default {
stranger,
frends,
thank,
"responds to good news":responds_to_good_news ,
}
