const irregularVerbs = [
  { word: "BE", translation: "SER / ESTAR" },
  { word: "BEAT", translation: "BATIR" },
  { word: "BECOME", translation: "LLEGAR A SER / CONVERTIRSE" },
  { word: "BEGIN", translation: "EMPEZAR" },
  { word: "BEND", translation: "DOBLAR" },
  { word: "BET", translation: "APOSTAR" },
  { word: "BITE", translation: "MORDER" },
  { word: "BLEED", translation: "SANGRAR" },
  { word: "BLOW", translation: "SOPLAR / EXPLOTAR" },
  { word: "BREAK", translation: "ROMPER" },
  { word: "BRING", translation: "TRAER" },
  { word: "BROADCAST", translation: "TRASMITIR" },
  { word: "BUILD", translation: "CONSTRUIR" },
  { word: "BURN", translation: "QUEMAR" },
  { word: "BURST", translation: "ESTALLAR / REVENTAR" },
  { word: "BUY", translation: "COMPRAR" },
  { word: "CAN", translation: "PODER" },
  { word: "CATCH", translation: "ATRAPAR" },
  { word: "CHOOSE", translation: "ELEGIR" },
  { word: "COME", translation: "VENIR" },
  { word: "COST", translation: "COSTAR" },
  { word: "CREEP", translation: "ARRASTRARSE" },
  { word: "CUT", translation: "CORTAR" },
  { word: "DEAL", translation: "NEGOCIAR" },
  { word: "DIG", translation: "CAVAR" },
  { word: "DO", translation: "HACER" },
  { word: "DRAW", translation: "DIBUJAR" },
  { word: "DREAM", translation: "SOÑAR" },
  { word: "DRINK", translation: "BEBER" },
  { word: "DRIVE", translation: "CONDUCIR" },
  { word: "EAT", translation: "COMER" },
  { word: "FALL", translation: "CAER" },
  { word: "FEED", translation: "ALIMENTAR" },
  { word: "FEEL", translation: "SENTIR" },
  { word: "FIGHT", translation: "LUCHAR" },
  { word: "FIND", translation: "ENCONTRAR" },
  { word: "FLEE", translation: "HUIR" },
  { word: "FLY", translation: "VOLAR" },
  { word: "FORBID", translation: "PROHIBIR" },
  { word: "FORGET", translation: "OLVIDAR" },
  { word: "FORGIVE", translation: "PERDONAR" },
  { word: "FREEZE", translation: "CONGELAR" },
  { word: "GET", translation: "CONSEGUIR" },
  { word: "GIVE", translation: "DAR" },
  { word: "GO", translation: "IR" },
  { word: "GROW", translation: "CRECER" },
  { word: "HANG", translation: "COLGAR" },
  { word: "HAVE", translation: "TENER" },
  { word: "HEAR", translation: "OIR" },
  { word: "HIDE", translation: "ESCONDER" },
  { word: "HIT", translation: "GOLPEAR / PEGAR" },
  { word: "HOLD", translation: "SUJETAR" },
  { word: "HURT", translation: "HERIR" },
  { word: "KEEP", translation: "GUARDAR / MANTENER" },
  { word: "KNEEL", translation: "ARRODILLARSE" },
  { word: "KNOW", translation: "SABER" },
  { word: "LAY", translation: "PONER" },
  { word: "LEAD", translation: "DIRIGIR" },
  { word: "LEAVE", translation: "DEJAR ALGO / IRSE" },
  { word: "LEND", translation: "PRESTAR" },
  { word: "LET", translation: "PERMITIR" },
  { word: "LIE", translation: "ACOSTARSE" },
  { word: "LIGHT", translation: "ILUMINAR / ENCENDER" },
  { word: "LOSE", translation: "PERDER" },
  { word: "MAKE", translation: "HACER" },
  { word: "MEAN", translation: "QUERER DECIR / SUPONER" },
  { word: "MEET", translation: "ENCONTRARSE" },
  { word: "PAY", translation: "PAGAR" },
  { word: "PUT", translation: "PONER" },
  { word: "READ", translation: "LEER" },
  { word: "RISE", translation: "ELEVAR" },
  { word: "RUN", translation: "CORRER" },
  { word: "SAY", translation: "DECIR" },
  { word: "SEE", translation: "VER" },
  { word: "SEND", translation: "ENVIAR" },
  { word: "SET", translation: "PREPARAR" },
  { word: "SEEK", translation: "BUSCAR" },
  { word: "SEW", translation: "COSER" },
  { word: "SHAKE", translation: "SACUDIR" },
  { word: "SHINE", translation: "BRILLAR" },
  { word: "SHOOT", translation: "DISPARAR" },
  { word: "SHOW", translation: "MOSTRAR" },
  { word: "SHRINK", translation: "ENCOGER" },
  { word: "SHUT", translation: "CERRAR" },
  { word: "SING", translation: "CANTAR" },
  { word: "SINK", translation: "HUNDIR" },
  { word: "SIT", translation: "SENTARSE" },
  { word: "SLEEP", translation: "DORMIR" },
  { word: "SLIDE", translation: "DESLIZAR" },
  { word: "SPEAK", translation: "HABLAR" },
  { word: "SPEND", translation: "GASTAR" },
  { word: "SPIT", translation: "ESCUPIR" },
  { word: "SPLIT", translation: "DIVIDIR" },
  { word: "STAND", translation: "PARARSE" },
  { word: "STEAL", translation: "ROBAR" },
  { word: "STICK", translation: "PEGAR" },
  { word: "STING", translation: "PICAR" },
  { word: "STINK", translation: "APESTAR" },
  { word: "SPRING", translation: "BROTAR" },
  { word: "STRIKE", translation: "ATACAR" },
  { word: "SWEAR", translation: "JURAR" },
  { word: "SWEEP", translation: "BARRER" },
  { word: "SWING", translation: "BALANCEARSE" },
  { word: "SWIM", translation: "NADAR" },
  { word: "TAKE", translation: "LLEVAR" },
  { word: "TEACH", translation: "ENSEÑAR" },
  { word: "TEAR", translation: "LAGRIMEAR" },
  { word: "TELL", translation: "DECIR" },
  { word: "THINK", translation: "PENSAR" },
  { word: "THROW", translation: "TIRAR / LANZAR" },
  { word: "UNDERSTAND", translation: "ENTENDER" },
  { word: "WEAR", translation: "VESTIR / LLEVAR PUESTO" },
  { word: "WEEP", translation: "LLORAR" },
  { word: "WRITE", translation: "ESCRIBIR" },
]

const regularVerbs = [
  { word: "ACT", translation: "ACTUAR" },
  { word: "ADD", translation: "AÑADIR / SUMAR" },
  { word: "ADDRESS", translation: "DIRIGIRSE" },
  { word: "ADVANCE", translation: "AVANZAR" },
  { word: "ALLOW", translation: "PERMITIR" },
  { word: "AMUSE", translation: "ENTRETENER" },
  { word: "ANNOY", translation: "MOLESTAR" },
  { word: "APOLOGIZE", translation: "DISCULPAR" },
  { word: "ARRIVE", translation: "LLEGAR" },
  { word: "ASK", translation: "PREGUNTAR" },
  { word: "ANSWER", translation: "RESPONDER" },
  { word: "APPEAR", translation: "APARECER" },
  { word: "ARREST", translation: "ARRESTAR" },
  { word: "ATTACK", translation: "ATACAR" },
  { word: "ASSIST", translation: "ASISTIR" },
  { word: "ASSURE", translation: "ASEGURAR" },
  { word: "AVOID", translation: "EVITAR" },
  { word: "BEG", translation: "SUPLICAR" },
  { word: "BEHAVE", translation: "COMPORTARSE" },
  { word: "BELIVE", translation: "CREER" },
  { word: "BELONG", translation: "PERTENECER" },
  { word: "BREATHE", translation: "RESPIRAR" },
  { word: "BRUSH", translation: "CEPILLAR" },
  { word: "CALL", translation: "LLAMAR" },
  { word: "CARE", translation: "CUIDAR" },
  { word: "CASH", translation: "COBRAR" },
  { word: "CARRY", translation: "LLEVAR" },
  { word: "CHANGE", translation: "CAMBIAR" },
  { word: "CHECK", translation: "COMPROBAR" },
  { word: "CLAIM", translation: "RECLAMAR" },
  { word: "CLEAN", translation: "LIMPIAR" },
  { word: "CLOSE", translation: "CERRAR" },
  { word: "COLLECT", translation: "RECOLECTAR" },
  { word: "COMBINE", translation: "COMBINAR" },
  { word: "COMMAND", translation: "MANDAR" },
  { word: "COMMIT", translation: "COMPROMETERSE / COMETER" },
  { word: "COMPARE", translation: "COMPARAR" },
  { word: "COMPLETE", translation: "COMPLETAR" },
  { word: "COMPOSE", translation: "COMPONER" },
  { word: "CONTAIN", translation: "CONTENER" },
  { word: "CONTINUE", translation: "CONTINUE" },
  { word: "COOK", translation: "COCINAR" },
  { word: "COUNT", translation: "CONTAR" },
  { word: "COPY", translation: "COPIAR" },
  { word: "CRASH", translation: "CHOCAR" },
  { word: "CRY", translation: "LLORAR" },
  { word: "CHARGE", translation: "CARGAR" },
  { word: "CROSS", translation: "CRUZAR" },
  { word: "DANCE", translation: "BAILAR" },
  { word: "DENY", translation: "DENEGAR" },
  { word: "DELIVER", translation: "ENTREGAR" },
  { word: "DEVOTE", translation: "DEDICAR" },
  { word: "DIE", translation: "MORIR" },
  { word: "DRESS", translation: "VESTIR" },
  { word: "DRY", translation: "SECAR" },
  { word: "DROP", translation: "DEJAR CAER" },
  { word: "ENJOY", translation: "DISFRUTAR" },
  { word: "EXCLAIM", translation: "EXCLAMAR" },
  { word: "EXPLAIN", translation: "EXPLICAR" },
  { word: "EXPRESS", translation: "EXPRESAR" },
  { word: "FAIL", translation: "FRACASAR" },
  { word: "FILE", translation: "ARCHIVAAR" },
  { word: "FILL", translation: "LLENAR" },
  { word: "FINISH", translation: "TERMINAR" },
  { word: "FIRE", translation: "DISPARAR" },
  { word: "FISH", translation: "PESCAR" },
  { word: "FIX", translation: "ARREGLAR" },
  { word: "FOLLOW", translation: "SEGUIR" },
  { word: "FRY", translation: "FREIR" },
  { word: "GUESS", translation: "ADIVINAR" },
  { word: "HAPPEN", translation: "SUCEDER" },
  { word: "HELP", translation: "AYUDAR" },
  { word: "HOPE", translation: "DESEAR" },
  { word: "IMAGINE", translation: "IMAGINAR" },
  { word: "JUDGE", translation: "JUZGAR" },
  { word: "KILL", translation: "MATAR" },
  { word: "KISS", translation: "BESAR" },
  { word: "LAUGH", translation: "REIR" },
  { word: "LIKE", translation: "GUSTAR" },
  { word: "LOOK", translation: "MIRAR" },
  { word: "MAINTAIN", translation: "MANTENER" },
  { word: "MANAGE", translation: "ADMINISTRAR" },
  { word: "MARRY", translation: "CASARSE" },
  { word: "MARK", translation: "MARCAR" },
  { word: "MASSAGE", translation: "MENSAJEAR" },
  { word: "MEASURE", translation: "MEDIR" },
  { word: "MISS", translation: "EXTRAÑAR" },
  { word: "MOVE", translation: "MOVER" },
  { word: "NAME", translation: "NOMBRAR" },
  { word: "NOTE", translation: "NOTAR" },
  { word: "NOTICIE", translation: "NOTIFICAR" },
  { word: "NUMBER", translation: "ENUMERAR" },
  { word: "OBSERVE", translation: "OBSERVAR" },
  { word: "OFFER", translation: "OFRECER" },
  { word: "OPEN", translation: "ABRIR" },
  { word: "ORDER", translation: "ORDENAR" },
  { word: "PASS", translation: "APROVAR" },
  { word: "PARK", translation: "APARCAR" },
  { word: "PERFORM", translation: "LLEVAR A CABO" },
  { word: "PHONE", translation: "TELEFONEAR" },
  { word: "PICK", translation: "RECOGER" },
  { word: "PLAN", translation: "PLANIFICAR" },
  { word: "PLAY", translation: "JUGAR" },
  { word: "PLEASE", translation: "COMPLACER" },
  { word: "PRACTICE", translation: "PRACTICAR" },
  { word: "PRAY", translation: "REZAR" },
  { word: "PREFER", translation: "PREFERIR" },
  { word: "PREPARE", translation: "PREPARAR" },
  { word: "PROMISE", translation: "PROMETER" },
  { word: "PRONOUNCE", translation: "PRONUNCIAR" },
  { word: "PUNISH", translation: "CASTIGAR" },
  { word: "PUSH", translation: "EMPUJAR" },
  { word: "RAIN", translation: "LLOVER" },
  { word: "RAISE", translation: "LEVANTAR" },
  { word: "RECEIVE", translation: "RECIBIR" },
  { word: "REFUSE", translation: "RECHAZAR" },
  { word: "REGISTER", translation: "REGISTRAR" },
  { word: "REMEMBER", translation: "RECORDAR" },
  { word: "REPAIR", translation: "REPARAR" },
  { word: "REPEAT", translation: "REPETIR" },
  { word: "REPORT", translation: "REPORTAR" },
  { word: "REQUEST", translation: "SOLICITAR" },
  { word: "REQUIRE", translation: "REQUERIR" },
  { word: "RESERVE", translation: "RESERVAR" },
  { word: "RESOLVE", translation: "RESOLVER" },
  { word: "SAIL", translation: "NAVEGAR" },
  { word: "SERVE", translation: "SERVIR" },
  { word: "SAVE", translation: "SALVAR" },
  { word: "SEARCH", translation: "BUSCAR" },
  { word: "SIGN", translation: "FIRMAR" },
  { word: "SMILE", translation: "SONREIR" },
  { word: "SMOKE", translation: "FUMAR" },
  { word: "SOUND", translation: "SONAR" },
  { word: "SPEL", translation: "DELETREAR" },
  { word: "START", translation: "COMENZAR" },
  { word: "STAY", translation: "PERMANECER" },
  { word: "STOP", translation: "DETENER" },
  { word: "STUDY", translation: "ESTUDIAR" },
  { word: "SUFFER", translation: "SUFRIR" },
  { word: "SURPRISE", translation: "SORPRENDER" },
  { word: "TALK", translation: "HABLAR" },
  { word: "TASTE", translation: "PROBAR" },
  { word: "TEST", translation: "TESTEAR" },
  { word: "THANK", translation: "AGRADECER" },
  { word: "TIE", translation: "ATAR" },
  { word: "TOUCH", translation: "TOCAR" },
  { word: "TRAIN", translation: "ENTRENAR" },
  { word: "TRASLATE", translation: "TRADUCIR" },
  { word: "TRAVEL", translation: "VIAJAR" },
  { word: "TRUST", translation: "CONFIAR" },
  { word: "TRY", translation: "INTENTAR" },
  { word: "UNIT", translation: "UNIR" },
  { word: "USE", translation: "USAR" },
  { word: "VARY", translation: "VARIAR" },
  { word: "VISIT", translation: "VISITAR" },
  { word: "WAIT", translation: "ESPERAR" },
  { word: "WALK", translation: "CAMINAR" },
  { word: "WANT", translation: "QUERER" },
  { word: "WARM", translation: "CALENTAR" },
  { word: "WASH", translation: "LAVAR" },
  { word: "WATCH", translation: "OBSERVAR / VER" },
  { word: "WATER", translation: "REGAR" },
  { word: "WEIGH", translation: "PESAR" },
  { word: "WHISTLE", translation: "SILBAR" },
  { word: "WISH", translation: "DESEAR" },
  { word: "WORK", translation: "TRABAJAR" },
  { word: "WORRY", translation: "PREOCUPARSE" },


  
]

export default {
  irregularVerbs,
  regularVerbs
}